/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm_clk.h"
#include "stm_uart.h"


struct RCC msi;
struct RCC hsi;
struct RCC hse;
struct RCC pll;
struct RCC sys;


struct USART usart;

char *buffer;





int main(void){
  init_msi(&msi);
  init_usart(&usart);

  config_msi_clock(&msi);
  config_hsi_clock(&hsi);
  config_hse_clock(&hse);
  config_pll_clock(&pll);
  configure_system_clock(&sys);
  uart_config_clock(&usart);

  buffer = "Testing USART\n\r";

  send_buffer(buffer);

  for(;;);


}
